from enum import StrEnum


class RunStatus(StrEnum):
    CREATED = "CREATED"
    RESOLVING_INTENT = "RESOLVING_INTENT"
    BUILDING_PLAN = "BUILDING_PLAN"
    VALIDATING_PLAN = "VALIDATING_PLAN"
    EXECUTING = "EXECUTING"
    WAITING_FOR_USER_CONTEXT = "WAITING_FOR_USER_CONTEXT"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    WAITING_FOR_EXTERNAL_JOB = "WAITING_FOR_EXTERNAL_JOB"
    SYNTHESIZING = "SYNTHESIZING"
    FINAL_SAFETY_VALIDATION = "FINAL_SAFETY_VALIDATION"
    REPAIRING_RESPONSE = "REPAIRING_RESPONSE"
    COMPLETED = "COMPLETED"
    COMPLETED_PARTIAL = "COMPLETED_PARTIAL"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_FINAL = "FAILED_FINAL"
    POLICY_BLOCKED = "POLICY_BLOCKED"
    CANCELED = "CANCELED"
    EXPIRED = "EXPIRED"


class StepStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED_FINAL = "FAILED_FINAL"
    CANCELED = "CANCELED"
    POLICY_BLOCKED = "POLICY_BLOCKED"


LEGACY_RUN_STATUS = {
    "CREATED": RunStatus.CREATED,
    "QUEUED": RunStatus.EXECUTING,
    "RUNNING": RunStatus.EXECUTING,
    "WAITING": RunStatus.WAITING_FOR_USER_CONTEXT,
    "COMPLETED": RunStatus.COMPLETED,
    "FAILED": RunStatus.FAILED_FINAL,
    "CANCELLED": RunStatus.CANCELED,
}


def legacy_run_status(value: str) -> RunStatus:
    try:
        return LEGACY_RUN_STATUS[str(value)]
    except KeyError as exc:
        raise ValueError("AGENT_RUN_STATUS_UNKNOWN") from exc
