from typing import Protocol

from .domain import CostProfile, CreditGrant, CreditLedgerEntry, CreditReservation, OperationType


class CostProfileRepository(Protocol):
    def get_active(self, operation_type: OperationType): ...
    def get_by_version(self, operation_type: OperationType, version: int): ...
    def create_version(self, profile: CostProfile): ...


class CreditLedgerRepository(Protocol):
    def append_entry(self, entry: CreditLedgerEntry): ...
    def list_user_entries(self, user_id: str): ...
    def find_by_idempotency(self, user_id: str, idempotency_key: str): ...


class CreditGrantRepository(Protocol):
    def create_grant(self, grant: CreditGrant): ...
    def list_spendable_grants(self, user_id: str): ...


class CreditReservationRepository(Protocol):
    def create_reservation(self, reservation: CreditReservation): ...
    def get(self, reservation_id: str): ...
