from app.agent_runtime.context_policy import ContextPolicy

CONTEXT_POLICIES_V1 = (
    ContextPolicy("CTX_EVIDENCE_INTAKE_V1", "EVIDENCE_INTAKE", frozenset({"CURRENT_MEDIA", "PET_PROFILE", "CAPTURE_MANIFEST"}), 20),
    ContextPolicy("CTX_FECES_CURRENT_V1", "FECES_CURRENT_ASSESSMENT", frozenset({"CURRENT_MEDIA", "PET_PROFILE", "OWNER_REPORTED", "CAPTURE_MANIFEST"}), 20),
    ContextPolicy("CTX_FECES_LONGITUDINAL_V1", "FECES_LONGITUDINAL_COMPARE", frozenset({"CURRENT_FECES_RESULT", "COMPATIBLE_FECES_HISTORY"}), 20),
    ContextPolicy("CTX_SYNTHESIS_V1", "FINAL_SYNTHESIS", frozenset({"VALIDATED_CLAIMS", "SAFETY_STATE", "EVIDENCE_REFERENCES"}), 50),
    ContextPolicy("CTX_CARE_FOLLOW_UP_V1", "CARE_FOLLOW_UP_PROPOSAL", frozenset({"VALIDATED_CLAIMS", "SAFETY_STATE", "CARE_CONTEXT"}), 20),
)
CONTEXT_POLICIES_BY_CAPABILITY = {p.capability_id: p for p in CONTEXT_POLICIES_V1}
