from enum import StrEnum


class RunStatus(StrEnum):
    CREATED = "CREATED"; RESOLVING_INTENT = "RESOLVING_INTENT"; BUILDING_PLAN = "BUILDING_PLAN"; VALIDATING_PLAN = "VALIDATING_PLAN"; EXECUTING = "EXECUTING"; WAITING_FOR_USER_CONTEXT = "WAITING_FOR_USER_CONTEXT"; WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"; WAITING_FOR_EXTERNAL_JOB = "WAITING_FOR_EXTERNAL_JOB"; SYNTHESIZING = "SYNTHESIZING"; FINAL_SAFETY_VALIDATION = "FINAL_SAFETY_VALIDATION"; REPAIRING_RESPONSE = "REPAIRING_RESPONSE"; COMPLETED = "COMPLETED"; COMPLETED_PARTIAL = "COMPLETED_PARTIAL"; FAILED_RETRYABLE = "FAILED_RETRYABLE"; FAILED_FINAL = "FAILED_FINAL"; POLICY_BLOCKED = "POLICY_BLOCKED"; CANCELED = "CANCELED"; EXPIRED = "EXPIRED"


ALLOWED_TRANSITIONS = {
    "CREATED": {"RESOLVING_INTENT", "POLICY_BLOCKED", "CANCELED"},
    "RESOLVING_INTENT": {"BUILDING_PLAN", "EXECUTING", "WAITING_FOR_USER_CONTEXT", "FAILED_FINAL"},
    "BUILDING_PLAN": {"VALIDATING_PLAN", "FAILED_FINAL"},
    "VALIDATING_PLAN": {"EXECUTING", "POLICY_BLOCKED", "FAILED_FINAL"},
    "EXECUTING": {"WAITING_FOR_USER_CONTEXT", "WAITING_FOR_APPROVAL", "WAITING_FOR_EXTERNAL_JOB", "SYNTHESIZING", "FAILED_RETRYABLE", "FAILED_FINAL", "CANCELED"},
    "WAITING_FOR_USER_CONTEXT": {"EXECUTING", "CANCELED", "EXPIRED"},
    "WAITING_FOR_APPROVAL": {"EXECUTING", "CANCELED", "EXPIRED"},
    "WAITING_FOR_EXTERNAL_JOB": {"EXECUTING", "FAILED_RETRYABLE", "CANCELED", "EXPIRED"},
    "SYNTHESIZING": {"FINAL_SAFETY_VALIDATION", "FAILED_RETRYABLE", "FAILED_FINAL"},
    "FINAL_SAFETY_VALIDATION": {"COMPLETED", "COMPLETED_PARTIAL", "REPAIRING_RESPONSE", "POLICY_BLOCKED"},
    "REPAIRING_RESPONSE": {"FINAL_SAFETY_VALIDATION", "FAILED_FINAL"},
}


def transition(current: RunStatus | str, target: RunStatus | str) -> RunStatus:
    current, target = str(current), str(target)
    if target not in ALLOWED_TRANSITIONS.get(current, set()):
        raise ValueError("AGENT_INVALID_STATE_TRANSITION")
    return RunStatus(target)
