from typing import Protocol

from .domain import MediaAsset, MediaUploadSession


class MediaAssetRepository(Protocol):
    def create_pending(self, asset: MediaAsset): ...
    def get_owned(self, user_id: str, media_id: str): ...
    def list_owned(self, user_id: str): ...
    def mark_ready(self, asset: MediaAsset): ...
    def mark_deleted(self, asset: MediaAsset): ...


class MediaUploadSessionRepository(Protocol):
    def create(self, session: MediaUploadSession): ...
    def get_owned(self, user_id: str, session_id: str): ...
    def mark_completed(self, session: MediaUploadSession): ...
