from enum import StrEnum


class DataClassification(StrEnum):
    REAL = "REAL"
    SYNTHETIC_DEMO = "SYNTHETIC_DEMO"
    TEST = "TEST"


class FeedbackValue(StrEnum):
    HELPED = "HELPED"
    NOT_QUITE = "NOT_QUITE"


class FeedbackReason(StrEnum):
    CLEAR = "CLEAR"
    ANSWERED_QUESTION = "ANSWERED_QUESTION"
    USEFUL_NEXT_STEP = "USEFUL_NEXT_STEP"
    USED_EVIDENCE_WELL = "USED_EVIDENCE_WELL"
    ACKNOWLEDGED_LIMITS = "ACKNOWLEDGED_LIMITS"
    RESPONSIBLY_REASSURING = "RESPONSIBLY_REASSURING"
    NOT_RELEVANT = "NOT_RELEVANT"
    TOO_GENERIC = "TOO_GENERIC"
    HARD_TO_UNDERSTAND = "HARD_TO_UNDERSTAND"
    REPETITIVE = "REPETITIVE"
    MISSED_EVIDENCE = "MISSED_EVIDENCE"
    INCORRECT_INTERPRETATION = "INCORRECT_INTERPRETATION"
    REPEATED_CONTEXT_REQUEST = "REPEATED_CONTEXT_REQUEST"
    TOO_SLOW = "TOO_SLOW"
    NO_CLEAR_NEXT_STEP = "NO_CLEAR_NEXT_STEP"
    SAFETY_CONCERN = "SAFETY_CONCERN"
    OTHER = "OTHER"


POSITIVE_FEEDBACK_REASONS = frozenset(
    {
        FeedbackReason.CLEAR,
        FeedbackReason.ANSWERED_QUESTION,
        FeedbackReason.USEFUL_NEXT_STEP,
        FeedbackReason.USED_EVIDENCE_WELL,
        FeedbackReason.ACKNOWLEDGED_LIMITS,
        FeedbackReason.RESPONSIBLY_REASSURING,
    }
)

NEGATIVE_FEEDBACK_REASONS = frozenset(set(FeedbackReason) - POSITIVE_FEEDBACK_REASONS)


class ResponseSourceType(StrEnum):
    AGENT_RUN = "AGENT_RUN"
    ANALYSIS = "ANALYSIS"
    SPECIALIST_ANALYSIS = "SPECIALIST_ANALYSIS"
    GROUNDED_ASSISTANT = "GROUNDED_ASSISTANT"
    WEEKLY_REPORT = "WEEKLY_REPORT"


class TraceStatus(StrEnum):
    STARTED = "STARTED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    POLICY_BLOCKED = "POLICY_BLOCKED"


class RufsState(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    UNKNOWN = "UNKNOWN"
    NOT_ELIGIBLE = "NOT_ELIGIBLE"


class LabPermission(StrEnum):
    VIEW_AGGREGATES = "LAB_VIEW_AGGREGATES"
    VIEW_TRACES = "LAB_VIEW_TRACES"
    VIEW_USER_CONTENT = "LAB_VIEW_USER_CONTENT"
    VIEW_FEEDBACK_COMMENTS = "LAB_VIEW_FEEDBACK_COMMENTS"
    REVIEW_CASES = "LAB_REVIEW_CASES"
    VIEW_AUDIT = "LAB_VIEW_AUDIT"


class ReviewStatus(StrEnum):
    OPEN = "OPEN"
    IN_REVIEW = "IN_REVIEW"
    RESOLVED = "RESOLVED"


class ReviewSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RollupGranularity(StrEnum):
    HOUR = "HOUR"
    DAY = "DAY"
