from typing import Any, Protocol


class AgentRepository(Protocol):
    def create_run_with_initial_step(self, run: dict[str, Any], step: dict[str, Any]) -> None: ...
    def get_run_owned(self, run_id: str, owner_user_id: str) -> dict[str, Any] | None: ...
    def transition_run(self, run_id: str, owner_user_id: str, expected_version: int, status: str) -> bool: ...
    def list_steps(self, run_id: str) -> list[dict[str, Any]]: ...
    def ensure_steps(self, run_id: str, steps: list[dict[str, Any]]) -> None: ...
    def cancel_steps(self, run_id: str) -> int: ...
    def claim_step(self, run_id: str, step_id: str, worker_id: str, now: Any, lease_seconds: int = 300) -> bool: ...
    def commit_step_result(self, run_id: str, step_id: str, worker_id: str, lease_epoch: int, result: dict[str, Any]) -> bool: ...
    def schedule_step_retry(self, run_id: str, step_id: str, worker_id: str, lease_epoch: int, now: Any) -> bool: ...
