const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const title = (eyebrow, heading, subtitle) => `<div class="eyebrow">${eyebrow}</div><h1 class="title">${heading}</h1><p class="subtitle">${subtitle}</p>`;

export function extendedView(route) {
  if (route === "ADMIN") return `${title("Administración","Estado operativo","Métricas técnicas protegidas para operadores autorizados.")}<section class="card"><div id="admin-status" class="empty"><strong>Comprobando permisos…</strong>No se muestran datos operativos hasta validar el rol.</div></section>`;
  if (route === "LIBRARY") return `${title("Biblioteca","Busca en la historia de tu mascota","Encuentra datos guardados y conserva siempre su procedencia.")}<section class="card"><form class="form" id="library-form"><label>Buscar<input id="library-query" required maxlength="200" placeholder="Ej. vacuna, peso o análisis"></label><button class="btn primary" type="submit">Buscar en mis fuentes</button><div id="library-status" class="footer-note"></div></form><div class="empty" style="margin-top:18px"><strong>Biblioteca basada en fuentes</strong>Las respuestas y resultados se limitan a la información guardada en tu cuenta.</div></section>`;
  if (route === "COLLABORATION") return `${title("Colaboración","Comparte el cuidado","Invita a una persona concreta con permisos limitados y caducidad opcional.")}<section class="card"><form class="form" id="collaboration-form"><label>Usuario invitado<input id="member-user" required maxlength="200" placeholder="ID de usuario o correo"></label><label>Rol<select id="member-role"><option value="CAREGIVER">Cuidador</option><option value="VIEWER">Solo lectura</option></select></label><label>Duración (horas)<input id="member-ttl" type="number" min="1" max="8760" placeholder="Opcional"></label><button class="btn primary" type="submit">Enviar invitación</button><div id="collaboration-status" class="footer-note"></div></form></section>`;
  if (route === "FEEDBACK") return `${title("Ayuda","Feedback y soporte","Cuéntanos qué ha ocurrido y te responderemos con contexto seguro.")}<section class="card"><form class="form" id="feedback-form"><label>Tipo<select id="feedback-category"><option value="FEEDBACK">Sugerencia</option><option value="BUG">Problema técnico</option><option value="SAFETY">Seguridad</option></select></label><label>Mensaje<textarea id="feedback-message" required maxlength="2000" rows="5" placeholder="Describe tu experiencia"></textarea></label><button class="btn primary" type="submit">Enviar feedback</button><div id="feedback-status" class="footer-note"></div></form></section>`;
  if (route === "PLANS") { const state = window.PETI_STATE || {}; const p = state.premium; const status = p?.entitlement_state || p?.entitlement || "Cargando"; return `${title("Plan PETi","Tu plan y tus límites","Consulta tu acceso sin confundir suscripción con seguridad clínica.")}<section class="card"><h2>${escapeHtml(status === "PREMIUM" ? "Plan Premium activo" : status === "FREE" ? "Plan gratuito" : "Estado pendiente")}</h2><p class="meta">${state.premiumError ? escapeHtml(state.premiumError) : "El estado lo determina el backend."}</p><div class="notice" style="margin-top:18px">Los resultados existentes y las funciones de seguridad no dependen de una suscripción.</div><button class="btn secondary" data-route="SETTINGS" type="button" style="margin-top:18px">Gestionar preferencias</button></section>`; }
  if (route === "SETTINGS") { const language = localStorage.getItem("peti.language") || "es"; const theme = localStorage.getItem("peti.theme") || "light"; return `${title("Ajustes","Preferencias","Adapta PETi a tu forma de cuidar.")}<section class="card"><div class="form"><label>Idioma<select id="language-setting"><option value="es" ${language === "es" ? "selected" : ""}>Español</option><option value="en" ${language === "en" ? "selected" : ""}>English</option></select></label><label>Tema<select id="theme-setting"><option value="light" ${theme === "light" ? "selected" : ""}>Claro</option><option value="dark" ${theme === "dark" ? "selected" : ""}>Oscuro</option></select></label><button class="btn primary" id="save-settings" type="button">Guardar preferencias</button><div id="settings-status" class="footer-note"></div></div></section>`; }
  if (route === "CARE") { const state = window.PETI_STATE || {}; const items = Array.isArray(state.care) ? state.care : []; const body = state.care === null ? "<div class=\"empty\">Cargando cuidados…</div>" : state.careError ? `<div class="notice">${escapeHtml(state.careError)}</div>` : items.length ? items.map((item) => `<div class="event"><time>${escapeHtml(item.due_at || "Fecha pendiente")}</time><div><h3>${escapeHtml(item.title)}</h3><p class="meta">${escapeHtml(item.category)}${item.notes ? ` · ${escapeHtml(item.notes)}` : ""}</p></div></div>`).join("") : "<div class=\"empty\"><strong>Sin eventos registrados</strong>Añade una medicación, paseo, vacuna o cita veterinaria para verla aquí.</div>"; return `${title("Cuidados","Calendario y Body Check","Organiza rutinas y revisiones sin convertirlas en diagnóstico.")}<div class="grid"><section class="card span-8"><h2>Próximos cuidados</h2><div class="timeline" style="margin-top:16px">${body}</div><form class="form" id="care-form" style="margin-top:18px"><label>Tipo<select id="care-category"><option value="MEDICATION">Medicación</option><option value="WALK">Paseo</option><option value="VACCINATION">Vacuna</option><option value="VETERINARY_VISIT">Cita veterinaria</option></select></label><label>Descripción<input id="care-title" required maxlength="120" placeholder="Ej. Vacuna anual"></label><label>Fecha y hora<input id="care-due" required type="datetime-local"></label><button class="btn primary" type="submit">Añadir evento</button><div id="care-status" class="footer-note"></div></form><div class="actions" style="margin-top:18px"><button class="btn secondary" type="button">Iniciar Body Check</button></div></section><section class="card span-4"><h2>Seguridad</h2><p class="meta">No es un diagnóstico. Las revisiones muestran señales observables y siempre indican cuándo consultar al veterinario.</p></section></div>`; }
  if (route === "RECORDS") { const state = window.PETI_STATE || {}; const items = Array.isArray(state.records) ? state.records : []; const body = state.records === null ? "<div class=\"empty\">Cargando documentos…</div>" : state.recordsError ? `<div class="notice">${escapeHtml(state.recordsError)}</div>` : items.length ? items.map((item) => `<div class="event"><time>${escapeHtml(item.document_date || item.created_at || "Fecha no disponible")}</time><div><h3>${escapeHtml(item.title || "Documento veterinario")}</h3><p class="meta">${escapeHtml(item.provider_name || item.document_type || "Fuente conservada")}</p><span class="badge">${escapeHtml(item.status || "Disponible")}</span></div></div>`).join("") : "<div class=\"empty\"><strong>No hay documentos todavía</strong>Los informes veterinarios y sus hechos extraídos aparecerán aquí con su origen.</div>"; return `${title("Documentos","Documentos y registros","Conserva fuentes visibles y revisa los hechos antes de guardarlos.")}<section class="card"><div class="actions"><button class="btn primary" data-route="SCAN" type="button">Subir documento</button><button class="btn secondary" data-route="HISTORY" type="button">Ver historial</button></div><div class="timeline" style="margin-top:18px">${body}</div></section>`; }
  if (route === "ASSISTANT") return `${title("Asistente PETi","Pregunta sobre tu historial","Respuestas basadas en las fuentes guardadas de tu mascota.")}<section class="card"><div class="notice"><strong>Asistente grounded</strong>Solo responderá con información relevante de tus registros y mostrará sus fuentes.</div><form class="form" id="assistant-form" style="margin-top:18px"><label>Pregunta<textarea id="assistant-question" rows="4" placeholder="¿Qué cambios aparecen en el historial reciente?"></textarea></label><button class="btn primary" type="submit">Consultar fuentes</button></form><div id="assistant-status" class="footer-note"></div></section>`;
  if (route === "BODY_CHECK") return `${title("Body Check","Revisión visible de bienestar","Marca únicamente lo que observes. PETi no diagnostica ni estima enfermedades.")}<section class="card"><div class="notice"><strong>Revisión pendiente</strong><br>Completa las observaciones con buena luz y detente si tu mascota se incomoda.</div><div class="grid" style="margin-top:18px">${["Ojos","Oídos","Piel y pelaje","Patas y postura","Respiración en reposo","Heces observables"].map((item) => `<label class="card span-6"><input type="checkbox" data-body-check="${escapeHtml(item)}"> <strong>${escapeHtml(item)}</strong><div class="meta">Sin señales visibles preocupantes</div></label>`).join("")}</div><div class="actions" style="margin-top:18px"><button class="btn primary" id="finish-body-check" type="button">Finalizar revisión</button><span id="body-check-status" class="footer-note"></span></div><p class="footer-note">Si detectas dolor, dificultad respiratoria, sangrado o un cambio intenso, contacta con un veterinario.</p></section>`;
  return "";
}

window.PETI_EXTENDED_VIEW = extendedView;

document.addEventListener("submit", async (event) => {
  const form = event.target;
  if (form.id !== "assistant-form") return;
  event.preventDefault();
  const state = window.PETI_STATE;
  const output = document.querySelector("#assistant-status");
  const question = document.querySelector("#assistant-question")?.value.trim();
  if (!state?.selectedPet) { output.textContent = "Añade una mascota antes de consultar el historial."; return; }
  if (!question) { output.textContent = "Escribe una pregunta."; return; }
  const api = window.PETI_API;
  if (!api) { output.textContent = "El API autenticado todavía no está disponible."; return; }
  output.textContent = "Consultando fuentes guardadas…";
  try {
    const answer = await api(`/v1/pets/${encodeURIComponent(state.selectedPet.id)}/assistant/grounded-answer`, { method: "POST", body: JSON.stringify({ question }) });
    const text = answer.answer || answer.response || answer.text || "No hay una respuesta grounded disponible.";
    output.innerHTML = `<div class="empty"><strong>Respuesta basada en fuentes</strong>${escapeHtml(text)}</div>`;
  } catch (_) {
    output.textContent = "No se pudo consultar el historial. Inténtalo de nuevo más tarde.";
  }
});

document.addEventListener("submit", async (event) => { const form = event.target; if (form.id !== "collaboration-form") return; event.preventDefault(); const output = document.querySelector("#collaboration-status"); const state = window.PETI_STATE; if (!state?.selectedPet) { output.textContent = "Añade una mascota antes de compartirla."; return; } if (!state.user?.getIdToken) { output.textContent = "La invitación se enviará al iniciar sesión."; return; } try { output.textContent = "Enviando invitación…"; const ttl = document.querySelector("#member-ttl").value; await window.PETI_API(`/v1/pets/${encodeURIComponent(state.selectedPet.id)}/collaboration/memberships`, { method: "POST", body: JSON.stringify({ member_user_id: document.querySelector("#member-user").value.trim(), role: document.querySelector("#member-role").value, ttl_hours: ttl ? Number(ttl) : null }) }); output.textContent = "Invitación creada con permisos limitados."; form.reset(); } catch (_) { output.textContent = "No se pudo crear la invitación. Revisa los datos e inténtalo de nuevo."; } });

document.addEventListener("click", (event) => { const button = event.target.closest("button"); if (!button || button.textContent.trim() !== "Iniciar Body Check") return; event.preventDefault(); const state = window.PETI_STATE; state.route = "BODY_CHECK"; location.hash = "BODY_CHECK"; window.PETI_RENDER?.(); });
document.addEventListener("click", async (event) => { if (event.target.id !== "finish-body-check") return; const total = document.querySelectorAll("[data-body-check]").length; const checked = [...document.querySelectorAll("[data-body-check]:checked")].map((box) => box.dataset.bodyCheck); const output = document.querySelector("#body-check-status"); if (checked.length !== total) { output.textContent = `Revisión incompleta: ${checked.length}/${total}. Completa solo lo que hayas observado.`; return; } const state = window.PETI_STATE; if (!state?.selectedPet?.id || !state.user?.getIdToken) { output.textContent = "Revisión completada en esta sesión; inicia sesión para guardarla en el historial."; return; } try { output.textContent = "Guardando observaciones…"; await window.PETI_API(`/v1/pets/${encodeURIComponent(state.selectedPet.id)}/care-records`, { method: "POST", body: JSON.stringify({ record_type: "BODY_CHECK_MANUAL", source: "OWNER_ENTERED", payload: { observations: checked, observed_at: new Date().toISOString(), provenance: { source_class: "OWNER_REPORTED", actor: "OWNER" } } }) }); output.textContent = "Revisión guardada en el historial como observación del cuidador."; } catch (_) { output.textContent = "No se pudo guardar la revisión. Inténtalo de nuevo más tarde."; } });

document.addEventListener("submit", async (event) => { const form = event.target; if (form.id !== "library-form") return; event.preventDefault(); const output = document.querySelector("#library-status"); const query = document.querySelector("#library-query").value.trim(); if (!query) { output.textContent = "Escribe algo para buscar."; return; } if (!window.PETI_STATE?.user?.getIdToken) { output.textContent = "La biblioteca se consultará al iniciar sesión."; return; } try { output.textContent = "Buscando en tus fuentes…"; const result = await window.PETI_API("/v1/search", { method: "POST", body: JSON.stringify({ query, pet_id: window.PETI_STATE.selectedPet?.id || null }) }); output.textContent = `${Array.isArray(result?.results) ? result.results.length : 0} resultados encontrados.`; } catch (_) { output.textContent = "No se pudo realizar la búsqueda. Inténtalo de nuevo más tarde."; } });

window.PETI_ADMIN_REFRESH = async () => { const output = document.querySelector("#admin-status"); if (!output) return; if (!window.PETI_STATE?.user?.getIdToken) { output.innerHTML = "<strong>Acceso restringido</strong>Inicia sesión con una cuenta autorizada."; return; } try { const metrics = await window.PETI_API("/v1/internal/ops/metrics"); output.innerHTML = `<strong>Métricas disponibles</strong><pre>${escapeHtml(JSON.stringify(metrics, null, 2))}</pre>`; } catch (_) { output.innerHTML = "<strong>Acceso restringido</strong>Esta vista requiere permisos de administración."; } };

document.addEventListener("click", (event) => {
  if (event.target.id !== "save-settings") return;
  const language = document.querySelector("#language-setting").value; const theme = document.querySelector("#theme-setting").value;
  window.PETI_I18N?.setLanguage(language); localStorage.setItem("peti.theme", theme); document.documentElement.dataset.theme = theme; window.PETI_RENDER?.();
  document.querySelector("#settings-status").textContent = "Preferencias guardadas en este dispositivo.";
});

document.addEventListener("submit", async (event) => {
  const form = event.target; if (form.id !== "feedback-form") return; event.preventDefault(); const output = document.querySelector("#feedback-status"); const state = window.PETI_STATE;
  if (!document.querySelector("#feedback-message").value.trim()) { output.textContent = "Escribe un mensaje antes de enviarlo."; return; }
  if (!state?.user?.getIdToken) { output.textContent = "El feedback se enviará al iniciar sesión."; return; }
  try { output.textContent = "Enviando…"; await window.PETI_API("/v1/support/cases", { method: "POST", body: JSON.stringify({ category: document.querySelector("#feedback-category").value, message: document.querySelector("#feedback-message").value.trim() }) }); output.textContent = "Feedback enviado. Gracias por ayudarnos a mejorar."; form.reset(); } catch (_) { output.textContent = "No se pudo enviar el feedback. Inténtalo de nuevo más tarde."; }
});

document.addEventListener("submit", async (event) => {
  const form = event.target;
  if (form.id !== "care-form") return;
  event.preventDefault();
  const state = window.PETI_STATE; const output = document.querySelector("#care-status");
  if (!state?.selectedPet) { output.textContent = "Añade una mascota antes de crear un cuidado."; return; }
  try { output.textContent = "Guardando evento…"; const due = new Date(document.querySelector("#care-due").value); await window.PETI_API(`/v1/pets/${encodeURIComponent(state.selectedPet.id)}/care`, { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ category: document.querySelector("#care-category").value, title: document.querySelector("#care-title").value.trim(), due_at: due.toISOString(), notification_enabled: false, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC", repeat_frequency: "ONCE", repeat_interval: 1 }) }); state.care = null; output.textContent = "Evento guardado."; window.location.hash = "CARE"; window.dispatchEvent(new HashChangeEvent("hashchange")); } catch (_) { output.textContent = "No se pudo guardar el evento. Inténtalo de nuevo."; }
});
